CREATE DATABASE db_top_player;

USE DATABASE db_top_player

CREATE TABLE usuarios(
	id INT(6) AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(120) NOT NULL,
	email VARCHAR(150) NOT NULL UNIQUE,
	senha_hash VARCHAR (255) NOT NULL,
	criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	  
);

CREATE TABLE jogos(
	id INT(6) AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(120) NOT NULL UNIQUE,
	genero VARCHAR(80) NOT null
);

CREATE TABLE players(
	id INT(6) AUTO_INCREMENT PRIMARY KEY,
	nickname VARCHAR(120) NOT NULL,
	plataforma ENUM ('PC','PS','XBOX', 'MOBILE', 'NINTENDO', 'OUTRO') NOT NULL DEFAULT 'OUTRO',
	criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE partidas(
	id INT(6) AUTO_INCREMENT PRIMARY KEY,
	jogo_id INT NOT NULL,
	player_id INT NOT NULL,
	pontos INT NOT NULL,
	data_partida DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (jogo_id) REFERENCES jogos(id) ON DELETE CASCADE,
	FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
);